### ISSUE TITLE
Build fails with rustc nightly (April 6, 2014) on OS X Mavericks

### ISSUE THREAD

**Issue by johnnyw** [ozkriff/marauder#1]
I tried building marauder using the instructions on the readme page:

./make_deps
make

But I get this error:
main.rs:13:1: 13:21 error: can't find crate for `cgmath`
main.rs:13 extern crate cgmath;

Additionally, when I comment out "extern crate cgmath", I get the same error for glfw, which seems to have been built using the make_deps script. At the end of make_deps' run, I get:

[100%] Built target glfw
mv: rename src/lib_.so_ to ../lib_.so_: No such file or directory

which leads me to believe something went wrong when trying to build glfw-rs. I'm fairly new to rust, and I'm guessing the problems I'm facing are due to a misunderstanding on my part about how the crates system works. Any help would be appreciated!

**Comment by Horki** [comment]
@ozkriff this can be closed also :+1:
